# This is a basic workflow to help you get started with Actions

name: CI-Load

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:  
 k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          options: -v ${{ github.workspace }}/k6-load-tests/:/k6-load-tests
          filename: k6-loal-tests/test-script.js
          flags: --out json=results.json

      - name: Upload performance test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-report
          path: results.json
