# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d

      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Build the stack
      - uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm ci --force
          npm install @wdio/selenium-standalone-service --save-dev
          npm i mocha-multi --force
          set NODE_ENV=${{ github.event.inputs.environment }}
          npx codeceptjs run  --steps --verbose
