# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name:  stack init
        run: docker swarm init
      - name:  swarm jointoken
        run: docker swarm join-token worker
      - name: Build the stack
        run: docker-compose up -d
      - name: check the stack
        run: docker ps 
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
         npm install
          npm ci --force
          npm install codeceptjs puppeteer --save
          npm i mocha-multi --force
          npx codeceptjs run --steps --verbose 
          
  
      - name: Generate Test Report
        run:  curl -o report.html "http://localhost:8090/JSON/reports/action/generate/?title=test&template=modern&theme=&description=&contexts=&sites=&sections=&includedConfidences=&includedRisks=&reportFileName=&reportFileNamePattern=&reportDir=&display"

      - name: Generate Test Report 
        run: |
             docker exec -t $(docker ps --format '{{.Names}}') /bin/bash
             ls /home/zap/
