# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
      runs-on: ubuntu-latest
      container:
        image: node:14.4
        options: --network-alias testHost
      env:
        NODE_ENV: test
        SELENIUM_HUB_HOST: hub
        TEST_HOST: testHost

      services:
        hub:
          image: selenium/hub:latest
        chrome:
          image: selenium/node-chrome:latest
          env:
            HUB_HOST: hub
            HUB_PORT: 4444

      strategy:
        matrix:
          node-version: [15.x]


      steps:
        - name: Start selenoid
          uses: Xotabu4/selenoid-github-action@v2
        - name: Setup NodeJS 14
          uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - run: |
            npm install
            npm ci --force
            npm install -g allure-commandline --save-dev
            npm install --save-dev webdriverio@^5.2.2
            npm i mocha-multi --force
            npx codeceptjs run --steps

